### ISSUE TITLE
Bad authorization url

### ISSUE THREAD

**Issue by rcpeters** [mozillascience/PaperBadger#134] opened 2015-09-27 21:57 UTC
url https://badges.mozillascience.org/issue is sending users to 
https://orcid.org/oauth/authorize/oauth/authorize?redirect_uri=https%3A%2F%2Fbadges.mozillascience.org%2Forcid_auth_callback&scope=%2Fauthenticate&state=none&response_type=code&client_id=APP-J4A352VNNL1J7UYB
when it should be sending people to:
https://orcid.org/oauth/authorize?redirect_uri=https%3A%2F%2Fbadges.mozillascience.org%2Forcid_auth_callback&scope=%2Fauthenticate&state=none&response_type=code&client_id=APP-J4A352VNNL1J7UYB
Notice the extra 'oauth/authorize/'

**Comment by acabunoc** [comment] 2015-09-27 22:53
Saw the same thing here: #132 -- I noticed it happens if users have logged in recently. I was hoping you'd have some insight.. i'll take a look later

**Comment by josmas** [comment] 2016-10-27 16:12
marking this as a duplicate of #132 as there's a bit more info in that issue (and it's the same problem).

**Closed by josmas** 2016-10-27 16:12 UTC
Labels: bug
